Project Name: Name
Scenes:
  - "":
      Models:
        bunny0:
          Transform:
            position:
              - 0
              - -1
              - 0
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 0.5
              - 0.5
              - 0.5
            shininess: 32
          Model:
            model_path: ../resources/models/bunny.obj
        bunny1:
          Transform:
            position:
              - -2
              - -1
              - -3
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 1
              - 1
              - 1
          Material:
            ambient:
              - 0.1
              - 0.1
              - 0.1
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 0.5
              - 0.5
              - 0.5
            shininess: 32
          Model:
            model_path: ../resources/models/bunny.obj
        bunny2:
          Transform:
            position:
              - 2.065
              - -1
              - -3
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 0.846
              - 0.999
              - 1
          Material:
            ambient:
              - 0.5058824
              - 0.101960786
              - 0.31764707
            diffuse:
              - 0
              - 0.8
              - 0.8
            specular:
              - 0.30588236
              - 0.6862745
              - 0.5019608
            shininess: 32
          Model:
            model_path: ../resources/models/bunny.obj
        square3:
          Transform:
            position:
              - 0.019
              - 0
              - -6.534
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 20
              - 20
              - 1
          Material:
            ambient:
              - 0.6156863
              - 0.101960786
              - 0.101960786
            diffuse:
              - 0.8
              - 0.8
              - 0.8
            specular:
              - 0.5
              - 0.5
              - 0.5
            shininess: 32
          Model:
            model_path: ../resources/models/square.obj
        teapot4:
          Transform:
            position:
              - 1.515
              - -0.714
              - 0
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 0.768
              - 0.751
              - 0.752
          Material:
            ambient:
              - 0
              - 0.101960786
              - 0.49019608
            diffuse:
              - 0.8
              - 0.50980395
              - 0.8
            specular:
              - 0.5019608
              - 0.6117647
              - 0.16862746
            shininess: 32
          Model:
            model_path: ../resources/models/teapot.obj
      Lights:
        "":
          Transform:
            position:
              - 0
              - 3
              - 0
            rotation:
              - 0
              - 0
              - 0
            scale:
              - 0
              - 0
              - 0
          Light:
            color:
              - 0.2
              - 0.2
              - 0.2
            intensity: 1